name: Demo
on:
  push:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: mlm-games/ci/.github/workflows/pages.yml@main
    with:
      working-directory: demo